<a href="https://colab.research.google.com/github/preetikumari5/Machine-Learning/blob/main/Matrix_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a matrix using numpy

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
a.shape

(2, 3)

In [4]:
b = np.array([[3,4,5,6],[4,5,6,7],[7,8,9,0]])
print(b)

[[3 4 5 6]
 [4 5 6 7]
 [7 8 9 0]]


In [5]:
b.shape

(3, 4)

Creating Matrices with random variables

In [6]:
c = np.random.rand(3,3)
print(c)

[[0.736301   0.21661678 0.1023044 ]
 [0.85018888 0.77572931 0.68084459]
 [0.10619092 0.52559755 0.9137589 ]]


In [9]:
d = np.random.randint(100,size=(4,5))
print(d)

[[81 97 29 25 63]
 [ 3 65 62 98 38]
 [50 88 83 35 89]
 [57 91  9 70 67]]


In [12]:
e = np.ones((2,3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
f = np.ones((2,3),dtype=int)
print(f)

[[1 1 1]
 [1 1 1]]


In [17]:
g = np.zeros((2,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
h = np.zeros((2,3),dtype=int)
print(h)

[[0 0 0]
 [0 0 0]]


In [20]:
i = np.eye(3,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
j = np.eye(3,3, dtype=int)
print(j)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
k = np.random.randint(10,size=(3,3))
print(k)

[[9 8 3]
 [2 1 6]
 [3 3 5]]


In [23]:
l = np.transpose(k)
print(l)

[[9 2 3]
 [8 1 3]
 [3 6 5]]
