<a href="https://colab.research.google.com/github/preetikumari5/Machine-Learning/blob/main/Matrix_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

ADDITION

In [2]:
a = np.random.randint(10,size=(2,2))
b = np.random.randint(11,20,size=(2,2))
print('A: ',a)
print('B: ',b)

A:  [[5 8]
 [4 2]]
B:  [[15 11]
 [14 16]]


In [3]:
sum = a+b
print(sum)

[[20 19]
 [18 18]]


In [4]:
c = np.add(a,b)
print(c)

[[20 19]
 [18 18]]


In [5]:
print(a.shape)
print(b.shape)
print(c.shape)

(2, 2)
(2, 2)
(2, 2)


SUBTRACTION

In [6]:
c = np.random.randint(10,size=(4,5))
d= np.random.randint(-10,10,size=(4,5))
print(c)
print(d)

[[3 2 7 0 7]
 [1 8 2 3 2]
 [6 9 8 6 9]
 [6 7 1 7 0]]
[[-1 -4  4 -8  0]
 [ 6  4  9  9  1]
 [ 9  0  6 -6  9]
 [ 5  9  5 -1 -5]]


In [7]:
e = c-d
print(e)

[[ 4  6  3  8  7]
 [-5  4 -7 -6  1]
 [-3  9  2 12  0]
 [ 1 -2 -4  8  5]]


In [8]:
e.shape

(4, 5)

In [9]:
diff = np.subtract(c,d)
print(diff)

[[ 4  6  3  8  7]
 [-5  4 -7 -6  1]
 [-3  9  2 12  0]
 [ 1 -2 -4  8  5]]


MULTIPLICATION

In [10]:
f = np.random.randint(10,size=(4,4))
g = np.random.randint(10,size=(4,4))
print(f)
print(g)

[[1 9 4 1]
 [5 6 1 4]
 [7 5 9 8]
 [2 9 1 1]]
[[9 5 1 7]
 [0 4 6 4]
 [9 2 0 9]
 [6 1 8 4]]


In [16]:
h = f*g
z = np.multiply(f,g)
print(h)
print(z)

[[ 9 45  4  7]
 [ 0 24  6 16]
 [63 10  0 72]
 [12  9  8  4]]
[[ 9 45  4  7]
 [ 0 24  6 16]
 [63 10  0 72]
 [12  9  8  4]]


In [12]:
h.shape

(4, 4)

In [13]:
i = np.dot(f,g)
print(i)

[[ 51  50  63  83]
 [ 78  55  73  84]
 [192  81 101 182]
 [ 33  49  64  63]]
