<a href="https://colab.research.google.com/github/preetikumari5/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of NumPy Arrays:
  1.   Allows severak mathematical operations
  2.   Faster operations






In [ ]:
import numpy as np

List vs NumPy - time taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range (10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001098505000000749


time taken by numpy array

In [ ]:
np_arr = np.array([i for i in range(10000)])
start_time = process_time()
np_arr = np_arr + 5
end_time = process_time()
print(end_time - start_time)

0.0024259200000003034


Numpy Arrays

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1 D array
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#no. of rows and cols
a.shape

(4,)

In [ ]:
#2D array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
#creating array of 0's
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#array of 1's
y = np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of particular value
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
#identity matrix
a = np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
#random values array
b = np.random.random((3,4))
print(b)

[[0.4699174  0.83156441 0.31940888 0.26944322]
 [0.53511889 0.8188856  0.95327909 0.69411015]
 [0.05073892 0.09447538 0.70969579 0.27341993]]


In [ ]:
#random integers
c = np.random.randint(1,10,(3,5))
print(c)

[[7 9 9 5 7]
 [2 3 4 3 2]
 [9 1 1 4 5]]


In [ ]:
#array of evenly spaced values --> giving number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# evenly spaced values --> giving space
e = np.arange(10,30,2)
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [ ]:
#convert list to array
list2 = [10,20,20,20,50]
print(list2)
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10, 20, 20, 20, 50]
[10 20 20 20 50]


numpy.ndarray

Analysing numpy array

In [ ]:
c = np.random.randint(10,90,(5,3))
print(c)

[[78 11 31]
 [38 84 41]
 [87 20 76]
 [86 48 81]
 [16 12 71]]


In [ ]:
#array dimension
print(c.shape)

(5, 3)


In [ ]:
#number of dimension
print(c.ndim)

2


In [ ]:
#number of element in array
print(c.size)

15


In [ ]:
#datatype of value
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 4 8]
 [7 1 2]
 [9 9 6]]
[[15 10 16]
 [12 10 10]
 [11 17 14]]


In [ ]:
print(a+b)

[[16 14 24]
 [19 11 12]
 [20 26 20]]


In [ ]:
print(a-b)

[[-14  -6  -8]
 [ -5  -9  -8]
 [ -2  -8  -8]]


In [ ]:
print(a*b)

[[ 15  40 128]
 [ 84  10  20]
 [ 99 153  84]]


In [ ]:
(print(a/b))

[[0.06666667 0.4        0.5       ]
 [0.58333333 0.1        0.2       ]
 [0.81818182 0.52941176 0.42857143]]


In [ ]:
print(np.add(a,b))

[[16 14 24]
 [19 11 12]
 [20 26 20]]


In [ ]:
print(np.subtract(a,b))

[[-14  -6  -8]
 [ -5  -9  -8]
 [ -2  -8  -8]]


In [ ]:
print(np.multiply(a,b))

[[ 15  40 128]
 [ 84  10  20]
 [ 99 153  84]]


In [ ]:
print(np.divide(a,b))

[[0.06666667 0.4        0.5       ]
 [0.58333333 0.1        0.2       ]
 [0.81818182 0.52941176 0.42857143]]


Array Manipulation

In [ ]:
arr1 = np.random.randint(0,10,(2,2))
print(arr1)
print(arr1.shape)

[[8 7]
 [6 5]]
(2, 2)


In [ ]:
#transpose
trans = np.transpose(arr1)
print(trans)
print(trans.shape)

[[8 6]
 [7 5]]
(2, 2)


In [ ]:
arr1 = np.random.randint(0,10,(2,2))
print(arr1)
print(arr1.shape)

[[8 3]
 [4 0]]
(2, 2)


In [ ]:
trans2 = arr1.T
print(trans2)
print(trans2.shape)

[[8 4]
 [3 0]]
(2, 2)


In [ ]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 3 5]
 [6 9 7]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 3]
 [5 6]
 [9 7]]
(3, 2)
